version: "3"

services:
  webapp:
    container_name: modyn_webapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - database
  database:
    container_name: modyn_db
    image: mongo
    ports:
      - "27018:27017"