services:
  webapp:
    container_name: modyn_webapp
    restart: always
    build: ./server
    ports:
      - "5000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env